# Generated by Django 3.2.9 on 2022-01-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistinctRateCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinct_city', models.CharField(max_length=200)),
                ('distinct_country', models.CharField(max_length=200)),
                ('distinct_counter', models.IntegerField()),
                ('distinct_overall', models.FloatField(null=True)),
                ('distinct_nightlife', models.FloatField()),
                ('distinct_food', models.FloatField()),
                ('distinct_culture', models.FloatField()),
                ('distinct_people', models.FloatField()),
                ('distinct_accommodation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RateCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('overall', models.FloatField(null=True)),
                ('nightlife', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Very Good')])),
                ('food', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Very Good')])),
                ('culture', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Very Good')])),
                ('people', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Very Good')])),
                ('accommodation', models.PositiveSmallIntegerField(choices=[(1, '1 - Very Bad'), (2, '2 - Bad'), (3, '3 - OK'), (4, '4 - Good'), (5, '5 - Very Good')])),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=200)),
                ('reg_pwd', models.CharField(max_length=200)),
                ('reg_pwd2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_address', models.CharField(max_length=200, null=True)),
                ('search_country', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_pwd', models.CharField(max_length=10)),
            ],
        ),
    ]
